use super::match_result::{MatchResult, MatchResultMultiple, MatchResultOptional, MatchResultSingle};

/// Snapshot projector for a [`MatchResultSingle`] bucket: given a bucket-level snapshot, return
/// the slot corresponding to one specific bound value.
///
/// The method's data lifetime `'d` is bound at the *call site*, so the bucket's natural lifetime
/// (e.g. `'src` in `(Option<&'src str>,)`) constrains `'d` per call rather than forcing the
/// whole bucket to be `'static` (as it would under an HRTB fn-pointer bound).
pub trait SingleSnapProj<Bucket, V>
where
    Bucket: MatchResultSingle,
{
    fn project<'a, 'd>(
        &self,
        snap: &'a mut Bucket::Snapshot<'d>,
    ) -> &'a mut Option<&'d V>
    where
        Bucket: 'd;
}

/// See [`SingleSnapProj`].
pub trait MultipleSnapProj<Bucket, V>
where
    Bucket: MatchResultMultiple,
{
    fn project<'a, 'd>(
        &self,
        snap: &'a mut Bucket::Snapshot<'d>,
    ) -> &'a mut Vec<&'d V>
    where
        Bucket: 'd;
}

/// See [`SingleSnapProj`].
pub trait OptionalSnapProj<Bucket, V>
where
    Bucket: MatchResultOptional,
{
    fn project<'a, 'd>(
        &self,
        snap: &'a mut Bucket::Snapshot<'d>,
    ) -> &'a mut Option<&'d V>
    where
        Bucket: 'd;
}

/// Zero-sized projector that addresses the `N`-th slot of a `Single` bucket snapshot.
///
/// `impl SingleSnapProj<...> for SingleSnapProjAt<N>` is generated by the
/// `impl_match_results_for_tuple!` macro for each concrete tuple shape.
#[derive(Clone, Copy)]
pub struct SingleSnapProjAt<const N: usize>;

/// See [`SingleSnapProjAt`].
#[derive(Clone, Copy)]
pub struct MultipleSnapProjAt<const N: usize>;

/// See [`SingleSnapProjAt`].
#[derive(Clone, Copy)]
pub struct OptionalSnapProjAt<const N: usize>;

/// Source location and name for debugging double-bind panics.
#[derive(Clone, Copy)]
pub struct BindDebugInfo {
    /// Name of the binding (from `bind!` / macro expansion).
    pub property_name: &'static str,
    /// File where the bind was created.
    pub file: &'static str,
    pub line: u32,
    pub column: u32,
}

/// Describes how to write a captured `Value` into the aggregate result `MRes`.
pub trait Property<Value, MRes>
where
    MRes: MatchResult,
{
    /// Store `value` into `result`, optionally using `debug` for panic messages on conflict.
    fn put_in_result(&self, result: &mut MRes, value: Value, debug: Option<BindDebugInfo>);
    /// Insert a reference to `value` into the corresponding slot of `snapshot`.
    ///
    /// The data lifetime of the inserted reference equals the lifetime of `value`, which
    /// must outlive the data lifetime of `snapshot`.
    fn put_ref_in_snapshot<'a>(&self, snapshot: &mut MRes::Snapshot<'a>, value: &'a Value);
    /// Remove `value` from `result`.
    fn remove_from_result(&self, result: &mut MRes, debug: Option<BindDebugInfo>);
    /// Wrap `value` with this property for deferred insertion into `MRes`.
    fn bind_result(&self, value: Value) -> super::bound::BoundValue<Value, Self>
    where
        Self: Sized,
        Self: Clone,
    {
        super::bound::BoundValue::new(value, self.clone(), None)
    }
    /// Like [`bind_result`](Self::bind_result) but attaches [`BindDebugInfo`] for diagnostics.
    fn bind_result_with_debug(
        &self,
        value: Value,
        debug: BindDebugInfo,
    ) -> super::bound::BoundValue<Value, Self>
    where
        Self: Sized,
        Self: Clone,
    {
        super::bound::BoundValue::new(value, self.clone(), Some(debug))
    }
}

/// Property that writes at most once into an `Option` field (panics if set twice).
#[derive(Clone, Copy)]
pub struct SingleProperty<FDirect, FSnapshot> {
    direct_setter: FDirect,
    snapshot_setter: FSnapshot,
}

impl<FDirect, FSnapshot> SingleProperty<FDirect, FSnapshot> {
    /// `setter` selects the `Option` slot inside the “single” capture bucket.
    pub fn new(direct_setter: FDirect, snapshot_setter: FSnapshot) -> Self {
        Self {
            direct_setter,
            snapshot_setter,
        }
    }
}

impl<V, MRes, FDirect, FSnapshot> Property<V, MRes> for SingleProperty<FDirect, FSnapshot>
where
    MRes: MatchResult,
    FDirect: Fn(&mut MRes::Single) -> &mut Option<V>,
    FSnapshot: SingleSnapProj<MRes::Single, V>,
{
    fn put_in_result(&self, result: &mut MRes, value: V, debug: Option<BindDebugInfo>) {
        let property_slot = (self.direct_setter)(result.single());
        if property_slot.is_some() {
            if let Some(debug) = debug {
                panic!(
                    "SingleProperty '{}' already set (bind! at {}:{}:{})",
                    debug.property_name, debug.file, debug.line, debug.column
                );
            }
            panic!("SingleProperty already set");
        }
        *property_slot = Some(value);
    }

    fn put_ref_in_snapshot<'a>(&self, snapshot: &mut MRes::Snapshot<'a>, value: &'a V) {
        let bucket = MRes::project_single_snapshot_mut(snapshot);
        let property_slot = self.snapshot_setter.project(bucket);
        if property_slot.is_some() {
            panic!("SingleProperty already set in snapshot");
        }
        *property_slot = Some(value);
    }

    fn remove_from_result(&self, result: &mut MRes, _debug: Option<BindDebugInfo>) {
        let property_slot = (self.direct_setter)(result.single());
        if property_slot.is_some() {
            *property_slot = None;
        } else {
            panic!("Trying to remove a value that was not set");
        }
    }
}

/// Property that appends each capture into a `Vec`.
#[derive(Clone, Copy)]
pub struct MultipleProperty<FDirect, FSnapshot> {
    direct_setter: FDirect,
    snapshot_setter: FSnapshot,
}

impl<FDirect, FSnapshot> MultipleProperty<FDirect, FSnapshot> {
    /// `setter` selects the `Vec` field inside the “multiple” capture bucket.
    pub fn new(direct_setter: FDirect, snapshot_setter: FSnapshot) -> Self {
        Self {
            direct_setter,
            snapshot_setter,
        }
    }
}

impl<V, MRes, FDirect, FSnapshot> Property<V, MRes> for MultipleProperty<FDirect, FSnapshot>
where
    MRes: MatchResult,
    FDirect: Fn(&mut MRes::Multiple) -> &mut Vec<V>,
    FSnapshot: MultipleSnapProj<MRes::Multiple, V>,
{
    fn put_in_result(&self, result: &mut MRes, value: V, _debug: Option<BindDebugInfo>) {
        let property_slot = (self.direct_setter)(result.multiple());
        property_slot.push(value);
    }

    fn put_ref_in_snapshot<'a>(&self, snapshot: &mut MRes::Snapshot<'a>, value: &'a V) {
        let bucket = MRes::project_multiple_snapshot_mut(snapshot);
        let property_slot = self.snapshot_setter.project(bucket);
        property_slot.push(value);
    }

    fn remove_from_result(&self, result: &mut MRes, _debug: Option<BindDebugInfo>) {
        let property_slot = (self.direct_setter)(result.multiple());
        if property_slot.pop().is_none() {
            panic!("Trying to remove a value that was not set");
        }
    }
}

/// Property for an optional capture stored in `Option` (panics if set twice).
#[derive(Clone, Copy)]
pub struct OptionalProperty<FDirect, FSnapshot> {
    direct_setter: FDirect,
    snapshot_setter: FSnapshot,
}

impl<FDirect, FSnapshot> OptionalProperty<FDirect, FSnapshot> {
    /// `setter` selects the `Option` slot inside the “optional” capture bucket.
    pub fn new(direct_setter: FDirect, snapshot_setter: FSnapshot) -> Self {
        Self {
            direct_setter,
            snapshot_setter,
        }
    }
}

impl<V, MRes, FDirect, FSnapshot> Property<V, MRes> for OptionalProperty<FDirect, FSnapshot>
where
    MRes: MatchResult,
    FDirect: Fn(&mut MRes::Optional) -> &mut Option<V>,
    FSnapshot: OptionalSnapProj<MRes::Optional, V>,
{
    fn put_in_result(&self, result: &mut MRes, value: V, debug: Option<BindDebugInfo>) {
        let property_slot = (self.direct_setter)(result.optional());
        if property_slot.is_some() {
            if let Some(debug) = debug {
                panic!(
                    "OptionalProperty '{}' already set (bind! at {}:{}:{})",
                    debug.property_name, debug.file, debug.line, debug.column
                );
            }
            panic!("OptionalProperty already set");
        }
        *property_slot = Some(value);
    }

    fn put_ref_in_snapshot<'a>(&self, snapshot: &mut MRes::Snapshot<'a>, value: &'a V) {
        let bucket = MRes::project_optional_snapshot_mut(snapshot);
        let property_slot = self.snapshot_setter.project(bucket);
        if property_slot.is_some() {
            panic!("OptionalProperty already set in snapshot");
        }
        *property_slot = Some(value);
    }

    fn remove_from_result(&self, result: &mut MRes, _debug: Option<BindDebugInfo>) {
        let property_slot = (self.direct_setter)(result.optional());
        if property_slot.is_some() {
            *property_slot = None;
        } else {
            panic!("Trying to remove a value that was not set");
        }
    }
}
